apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: blocky
  namespace: default
spec:
  repo: https://k8s-at-home.com/charts/
  chart: blocky
  version: 9.0.3
  valuesContent: |
    hostNetwork: true
    nodeSelector:
      kubernetes.io/hostname: k3sb
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "4000"
      prometheus.io/path: "/metrics"
    env:
      TZ: Europe/Amsterdam
    config: |
      upstream:
        default:
          - 1.0.0.1
          - 1.1.1.1
      customDNS:
        mapping:
          k3sa: 192.168.1.4
          k3sb: 192.168.1.3
      blocking:
        # definition of blacklist groups. Can be external link (http/https) or local file
        blackLists:
          ads:
            - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
            - https://hosts-file.net/ad_servers.txt
            - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
            - https://mirror1.malwaredomains.com/files/justdomains
            - http://sysctl.org/cameleon/hosts
            - https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
            - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
            - https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt
        whiteLists:
            ads:
              - |
                # inline definition with YAML literal block scalar style
                # hosts format
                www.googleadservices.com
                googleadservices.com
                # this is a regex
                /^banners?[_.-]/
        clientGroupsBlock:
          default:
            - ads
            - special
      prometheus:
        enable: true
        path: /metrics
      port: 53
      httpPort: 4000
      disableIPv6: true