{
 "title": "Blocky",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "blocky_url", "label": "blocky API URL", "query": "http://k3sb:4000" }
  ]
 },
 "panels": [
  {
   "title": "State",
   "type": "stat",
   "description": "current service state",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{app_kubernetes_io_name=\"blocky\"})"
    }
   ]
  },
  {
   "title": "Blocking",
   "type": "stat",
   "description": "Is blocking enabled?",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "blocky_blocking_enabled" }
   ]
  },
  {
   "title": "Blocking status",
   "type": "text",
   "description": "Enable od disable blocking",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<style>\n\n.blocky_btn {\n    border: none;\n  cursor: pointer; \n    padding: 12px;\n  font-size: 16px;\n  min-width: 100px\n}\n\n.blocky_greenbtn { \n  background-color: #4CAF50;\n  color: white;\n}\n\n.blocky_redbtn { \n  background-color: #AF504C;\n  color: white;\n}\n\n\n.blocky_alert {\n  font-size: 14px\n}\n</style>\n<div class=\"blocky_alert blocky_alert-warning fade in\">\n  <a href=\"#\" class=\"close\" data-dismiss=\"blocky_alert\" aria-label=\"close\" style=\"text-decoration:none\">&times;</a>Done!\n</div>\n<div>\n   <button class=\"blocky_btn blocky_greenbtn\" onclick=\"blocky_status_enable()\">On</button>\n   <button class=\"blocky_btn blocky_redbtn\" onclick=\"blocky_status_disable5m()\">Off 5m</button>\n   <button class=\"blocky_btn blocky_redbtn\" onclick=\"blocky_status_disable30m()\">Off 30m</button>\n<div>\n\n\n<script type=\"text/javascript\">\n\nfunction blocky_status_disable() {\n  blocky_status_switch(false, 0)\n}\n\nfunction blocky_status_disable5m() {\n  blocky_status_switch(false, 5*60)\n}\n\nfunction blocky_status_disable30m() {\n  blocky_status_switch(false, 30*60)\n}\n\nfunction blocky_status_enable() {\n  blocky_status_switch(true, 0)\n}\n\nfunction blocky_status_switch(enable, duration) {\n  var url = '$blocky_url';\n  op = enable ? 'enable' : 'disable?duration='+duration+\"s\"\n  $.get(url + '/api/blocking/'+op, function(data) {\n    showAlert()\n  })\n   .fail(function() {\n    alert( \"error\" );\n  })\n}\n\nvar showAlert = function() {\n\t// first show the alert\n  $('.blocky_alert').show().fadeTo(500, 1);\n  \n  // Now set a timeout to hide it\n  window.setTimeout(function() {\n    $(\".blocky_alert\").fadeTo(500, 0).slideUp(500, function() {\n      $(this).hide();\n    });\n  }, 3000);\n}\n\n// start with the alert hidden\n$('.blocky_alert').hide();\n\n</script>"
   }
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "Blocky [version](https://github.com/0xERR0R/blocky) number",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "blocky_build_info " }
   ]
  },
  {
   "title": "Avg response time",
   "type": "stat",
   "description": "Average query response time for all query types",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_request_duration_ms_sum[$__range])) / sum(increase(blocky_request_duration_ms_count[$__range]))"
    }
   ]
  },
  {
   "title": "Blacklist entries total",
   "type": "stat",
   "description": "Number of blacklist entries",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "blocky_blacklist_cache" }
   ]
  },
  {
   "title": "Memory allocated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_sys_bytes{app_kubernetes_io_name=\"blocky\"})/sum(up{app_kubernetes_io_name=\"blocky\"})"
    }
   ]
  },
  {
   "title": "Queries blocked",
   "type": "stat",
   "description": "Percentage of blocked queries",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_response_total{response_type=\"BLOCKED\"}[$__range])) / sum(increase(blocky_query_total[$__range])) "
    }
   ]
  },
  {
   "title": "Query Count Total",
   "type": "stat",
   "description": "Number of all queries. Shows the last value",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(blocky_query_total[$__range]))) "
    }
   ]
  },
  {
   "title": "Cache entries count",
   "type": "stat",
   "description": "Number of entries in the cache. Shows the last value",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "blocky_cache_entry_count" }
   ]
  },
  {
   "title": "Cache Hit/Miss ratio",
   "type": "stat",
   "description": "Cache Hit/Miss ratio. 100 % means, all queries could be answered from the cache, 0% - all queries must be resolved via external DNS",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_cache_hit_count[$__range])) / (sum(increase(blocky_cache_hit_count[$__range])) + sum(increase(blocky_cache_miss_count[$__range])))"
    }
   ]
  },
  {
   "title": "Error count",
   "type": "stat",
   "description": "Number of occured errors",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_error_total[$__range]))"
    }
   ]
  },
  {
   "title": "Prefetch count",
   "type": "stat",
   "description": "Amount of performed DNS queries to prefetch cached queries",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(blocky_prefetch_count[$__range])))"
    }
   ]
  },
  {
   "title": "Prefetch rate per min",
   "type": "stat",
   "description": "Amount of prefetch queries per minute",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(blocky_prefetch_count[5m])) * 60"
    }
   ]
  },
  {
   "title": "Prefetch Hit ratio",
   "type": "stat",
   "description": "How many of cached entries were prefetched automatically",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_prefetch_hit_count[$__range])) / (sum(increase(blocky_cache_hit_count[$__range])))"
    }
   ]
  },
  {
   "title": "Last list refresh",
   "type": "stat",
   "description": "Time since last list refresh",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() -blocky_last_list_group_refresh"
    }
   ]
  },
  {
   "title": "Prefetch domain count",
   "type": "stat",
   "description": "Amount of unique domains in the prefetched cache",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blocky_prefetch_domain_name_cache_count"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "avg requests / min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(blocky_query_total[5m])) * 60",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Request rate per client",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "avg requests / min" }
   ],
   "targets": [
    {
     "expr": "sum by (client) (rate(blocky_query_total[5m])) * 60",
     "legendFormat": " {{client}}"
    }
   ]
  },
  {
   "title": "request duration (upstream)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(increase(blocky_request_duration_ms_bucket{response_type=\"RESOLVED\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes Nodes",
 "description": "Kubernetes Nodes for node exporter 0.16+ (via Prometheus)\r\n",
 "tags": [
  "nodes",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": {
     "query": "label_values(node_boot_time_seconds, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Idle CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", instance=\"$server\"}[5m])) * 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"$server\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{instance=\"$server\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{instance=\"$server\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$server\"} - node_memory_MemFree_bytes{instance=\"$server\"} - node_memory_Buffers_bytes{instance=\"$server\"} - node_memory_Cached_bytes{instance=\"$server\"}",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$server\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$server\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$server\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"$server\"} - node_memory_MemFree_bytes{instance=\"$server\"}  - node_memory_Buffers_bytes{instance=\"$server\"} - node_memory_Cached_bytes{instance=\"$server\"}) / node_memory_MemTotal_bytes{instance=\"$server\"}) * 100"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_nfsd_disk_bytes_read_total{instance=\"$server\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by (instance) (rate(node_nfsd_disk_bytes_written_total{instance=\"$server\"}[2m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_io_time_seconds_total{instance=\"$server\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\",instance=\"$server\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\",instance=\"$server\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\",instance=\"$server\"})"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$server\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$server\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}
{
 "title": "Deployment & Statefulset",
 "description": "Monitors Kubernetes deployments in cluster using Thanos. Shows overall cluster CPU / Memory of deployments, replicas in each deployment. Uses Kube state metrics and cAdvisor metrics ",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_last_seen, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_last_seen{namespace =\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_last_seen{namespace =\"$namespace\", pod=~\"$pod\"}, container)"
    }
   },
   { "name": "Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Total usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory utilization",
   "type": "stat",
   "description": "Max per containers in a pod",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"$pod\", namespace=\"$namespace\", container=~\"$container\"}) by (pod,container) / sum(container_spec_memory_limit_bytes{pod=~\"$pod\", namespace=\"$namespace\", container=~\"$container\"}) by (container, pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "stat",
   "description": "Max per containers in a pod",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_cpu_usage_cores{pod=~\"^$pod$\", namespace=\"$namespace\", container=~\"^$container$\"}) by (pod,container) / sum(kube_pod_container_resource_limits_cpu_cores{pod=~\"^$pod$\", namespace=\"$namespace\", container=~\"^$container$\"}) by (container, pod)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{container!=\"POD\",pod=~\"^$pod$\", namespace=~\"^$namespace$\", container=~\"^$container$\"}[5m])) by (pod, container)",
     "legendFormat": "{{ pod }} | {{ container }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{id!=\"/\",pod=~\"^$pod$\", namespace=~\"^$namespace$\", container=~\"^$container$\"})  by (pod, container)",
     "legendFormat": "{{ pod }} | {{ container }}"
    },
    {
     "expr": "min (container_spec_memory_reservation_limit_bytes{pod=~\"^$pod$\", namespace=~\"^$namespace$\", container=~\"^$container$\"})  by (container)",
     "legendFormat": "requests: {{ container }}"
    },
    {
     "expr": "min (container_spec_memory_limit_bytes{pod=~\"^$pod$\", namespace=~\"^$namespace$\", container=~\"^$container$\"})  by (container)",
     "legendFormat": "limits: {{ container }}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory usage by types",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_rss{id!=\"/\",pod=~\"^$pod$\", namespace=~\"^$namespace$\", container=~\"^$container$\"})  by (pod, container)",
     "legendFormat": "rss: {{pod}} | {{container}}"
    },
    {
     "expr": "sum (container_memory_cache{id!=\"/\",pod=~\"^$pod$\", namespace=~\"^$namespace$\", container=~\"^$container$\"})  by (pod, container)",
     "legendFormat": "cache: {{pod}} | {{container}}"
    },
    {
     "expr": "sum (container_memory_swap{id!=\"/\",pod=~\"^$pod$\", namespace=~\"^$namespace$\", container=~\"^$container$\"})  by (pod, container) > 0",
     "legendFormat": "swap: {{pod}} | {{container}}"
    }
   ]
  },
  {
   "title": "Memory limit hits",
   "type": "graph",
   "description": "Number of memory usage hits limits",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_memory_failcnt{id!=\"/\",pod=~\"^$pod$\", namespace=~\"^$namespace$\", container=~\"^$container$\"}[2m]))  by (pod, container)",
     "legendFormat": "{{pod}} | {{container}}"
    }
   ]
  },
  {
   "title": "Memory page faults",
   "type": "graph",
   "description": "Number of memory usage hits limits",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_memory_failures_total{id!=\"/\",pod=~\"^$pod$\", namespace=~\"^$namespace$\", container=~\"^$container$\"}[5m]))  by (pod, container, type)",
     "legendFormat": "{{type}}: {{pod}} | {{container}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Network bytes sent/received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",pod=~\"^$pod$\", namespace=~\"^$namespace$\"}[5m])) by (pod)",
     "legendFormat": "received: {{ pod }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",pod=~\"^$pod$\", namespace=~\"^$namespace$\"}[5m])) by (pod)",
     "legendFormat": "sent: {{ pod }}"
    }
   ]
  },
  { "title": "File System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "File system bytes read/write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod=~\"^$pod$\", namespace=~\"^$namespace$\", container=~\"^$container$\"}[5m])) by (pod, container)",
     "legendFormat": "read: {{ pod }} | {{container}}"
    },
    {
     "expr": "-sum(rate(container_fs_writes_bytes_total{pod=~\"^$pod$\", namespace=~\"^$namespace$\", container=~\"^$container$\"}[5m])) by (pod, container)",
     "legendFormat": "write: {{ pod }} | {{container}}"
    }
   ]
  }
 ]
}