apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: omada-controller
  namespace: default
spec:
  repo: https://k8s-at-home.com/charts/
  chart: omada-controller
  version: 4.0.1
  valuesContent: |
    hostNetwork: true
    nodeSelector:
      kubernetes.io/hostname: k3sb
    env:
      TZ: Europe/Amsterdam
    persistence:
      data:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 1Gi