---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timemachine
  namespace: default
spec:
  serviceName: timemachine
  replicas: 1
  selector:
    matchLabels:
      app: timemachine
  template:
    metadata:
      labels:
        app: timemachine
    spec:
      hostNetwork: true
      containers:
      - name: timemachine
        env:
        - name: VOLUME_SIZE_LIMIT
          value: 1T
        - name: SET_PERMISSIONS
          value: "true"
        - name: ADVERTISED_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: mbentley/timemachine:smb-20211004
        volumeMounts:
          - mountPath: /opt
            name: data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Ti
